version: '2'
services:
    openpar-app:
        image: openpar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://openpar-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=openpar
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    openpar-mongodb:
        extends:
            file: mongodb.yml
            service: openpar-mongodb
